### ISSUE TITLE
Added Septapus to my Discord Server, Stopped Working After a few hours

### ISSUE THREAD

**Issue by TyGoss** [iopred/bruxism#10]
It was working most of the day, but now it won't respond to any commands for some reason.

When you type @septapus comic it says "Septapus is typing" but then nothing happens.

@septapus help doesn't do anything anymore either.

Thoughts?

**Comment by iopred** [comment]
Sorry about that, Discord started enforcing new Bot behavior and I'm lazy, should be fixed now.
