### ISSUE TITLE
Latest versions of this are broken

### ISSUE THREAD

**Issue by xXBuilderBXx** [iopred/bruxism#11]
The latest version of this is broken and will not download when you try go git
Git Bash is saying this

$ go get github.com/iopred/bruxism/cmd/bruxism
# github.com/iopred/bruxism/playedplugin
C:\Go\bin\src\github.com\iopred\bruxism\playedplugin\playedplugin.go:114: cannot convert nil to type bool
C:\Go\bin\src\github.com\iopred\bruxism\playedplugin\playedplugin.go:114: invalid indirect of g.Guild.Unavailable (type bool)

**Comment by iopred** [comment]
Should be good, sorry about that.
