### ISSUE TITLE
Discord command errors

### ISSUE THREAD

**Issue by xXBuilderBXx** [iopred/bruxism#13]
I am getting this error when running @BotName (Command)

Error sending discord message:  HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}

**Comment by xXBuilderBXx** [comment]
Soz if i am disturbing you with all this help ^_^

**Comment by iopred** [comment]
Discord requires your token to look like "Bot <token>" now.. so your
startup should look like:

./bruxism -discordtoken "Bot somethingsomethingsomething"

**Comment by xXBuilderBXx** [comment]
When i am doing bruxism -discordtoken (TokenStuff) i am getting chat messages from discord but the commands are now working

**Comment by iopred** [comment]
You need "'s around "Bot <token>"

**Comment by xXBuilderBXx** [comment]
Ok thanks it works now
