### ISSUE TITLE
How to use youtube commands?

### ISSUE THREAD

**Issue by xXBuilderBXx** [iopred/bruxism#14]
Sorry to bother you again but how do you use the commands for the youtube one i have been trying to do !help but the chat only apears in the console window and does nothing else. Also how can i setup alerts for when a livestream is online

**Comment by iopred** [comment]
I've got to update the docs, but they work the same as Discord:
@channelname help

You'll have to modify the liveplugin to do announcing, or just use Septapus:
@septapus setyoutubechannel <channel id>
@septapus setdiscordchannel

**Comment by xXBuilderBXx** [comment]
Are you supposed to have a custom url for the youtube channel because both septus and @channelname did not work
Septus is not notifying when a stream is live when i input the channel id
@channelname is not doing anything but chat is still shown in console

**Comment by iopred** [comment]
I mean the name of your channel you authorized the bot with.. so in my case:

@iopred help

**Comment by iopred** [comment]
If you just want to announce going live, invite Septapus to your Discord:
http://www.septapus.com

**Comment by xXBuilderBXx** [comment]
I have tried to set them up septus is in my discord with full perms, youtube channel and discord channel but no notification. Also i have a space in my name so does that mean i have to use underscore?

**Comment by iopred** [comment]
Message me an invite to your discord and I'll try help out.

**Comment by xXBuilderBXx** [comment]
https://discord.gg/TQzbA
