### ISSUE TITLE
Bruxism setup help

### ISSUE THREAD

**Issue by UnforeseenOcean** [iopred/bruxism#16]
I followed the instruction shown in the README.md, then after I managed to register oAuth2, it displayed nothing.
After mistyping command it displayed list of commands so it is not like the thing is corrupted, but after successful(?) command it does not display anything. I am using Git Bash.
Plus, I am having trouble setting it up...
- I have set up a bot account for this but so far I can't interact with it. What am I doing wrong?
- The build I used was 16 commits behind, so how do I update my installation?
- How do I personalize Bruxism? A "modding" guide would be greatly appreciated.
- Are plugins pre-installed or do I have to install them manually? And how do I install them?

**Comment by UnforeseenOcean** [comment]
Command output (sanitized) :

`user@user-PC MINGW64 /c/Go/bin
$ go get github.com/iopred/bruxism/cmd/bruxism
warning: GOPATH set to GOROOT (C:\Go\) has no effect

user@user-PC MINGW64 /c/Go/bin
$ go install github.com/iopred/bruxism/cmd/bruxism
warning: GOPATH set to GOROOT (C:\Go\) has no effect

user@user-PC MINGW64 /c/Go/bin
$ bruxism -youtubeauth AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
2016/10/01 20:58:41 Error creating service YouTube: googleapi: Error 403: Access 
Not Configured. YouTube Data API has not been used in project 111111111111 befo
re or it is disabled. Enable it by visiting https://console.developers.google.co
m/apis/api/youtube/overview?project=111111111111 then retry. If you enabled this 
API recently, wait a few minutes for the action to propagate to our systems and 
retry., accessNotConfigured


user@user-PC MINGW64 /c/Go/bin
$ bruxism -youtubeauth AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
2016/10/01 21:02:31 Error creating service YouTube: googleapi: Error 403: Access 
Not Configured. YouTube Data API has not been used in project 111111111111 befo
re or it is disabled. Enable it by visiting https://console.developers.google.co
m/apis/api/youtube/overview?project=111111111111 then retry. If you enabled this 
API recently, wait a few minutes for the action to propagate to our systems and 
retry., accessNotConfigured


user@user-PC MINGW64 /c/Go/bin
$ bruxism -youtubeurl
2016/10/01 21:05:14 Visit the following URL to generate an auth code, then rerun 
with -auth=<code> (It has also been copied to your clipboard):
%s https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt
=force&client_id=1111111111111-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.apps.googleuserco
ntent.com&redirect_uri=aaa%3Aaaaa%3Aaa%3Aoauth%3A2.0%3Aoob&response_type=code&sc
ope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube&state=state

user@user-PC MINGW64 /c/Go/bin
$ bruxism -youtubeauth AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA


user@user-PC MINGW64 /c/Go/bin
$ bruxism
bruxism -discordtoken AAAAAAAAAAAAAAAAAAAAAAAAAAA


user@user-PC MINGW64 /c/Go/bin
$ bruxism -discordtoken AAAAAAAAAAAAAAAAAAAAAAAAAAA
2016/10/01 21:15:33 [DG0] wsapi.go:697:Close() error closing websocket, websocke
t: close sent


user@user-PC MINGW64 /c/Go/bin
$ bruxism -discordapplicationclientid 111111111111111111


user@user-PC MINGW64 /c/Go/bin
$ bruxism -discordtoken AAAAAAAAAAAAAAAAAAAAAAAAAAA
2016/10/01 21:29:35 [DG0] wsapi.go:697:Close() error closing websocket, websocket: close sent
2016/10/01 21:29:36 [DG0] wsapi.go:706:Close() error closing websocket, write tcp 192.168.123.4:58413->123.45.67.89:443: i/o timeout
2016/10/01 21:29:38 [DG0] wsapi.go:697:Close() error closing websocket, websocket: close sent


user@user-PC MINGW64 /c/Go/bin
$ bruxism -discordtoken AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`

**Comment by iopred** [comment]
2 things:

1) It looks like you need to enable the youtube api, follow the
instructions in your log up there.
2) Your bot token has to be set like:
bruxism -discordtoken "Bot AAAAAAAAA"

**Comment by UnforeseenOcean** [comment]
YouTube API has been set up and saved, but this does not output anything.
I reinstalled Go and reset the global variables to C:\Go, just to be sure.

Does this have verbose output?

**Comment by UnforeseenOcean** [comment]
Oh, and the bot in read-only mode(?) crashed with this error here:
`fatal error: concurrent map read and map write

goroutine 1 [running]:
runtime.throw(0x8b8796, 0x21)
        C:/Go/src/runtime/panic.go:566 +0x9c fp=0xc04222b3b0 sp=0xc04222b390
runtime.mapaccess2(0x815560, 0xc0421ee510, 0xc042d9efc0, 0xc04222b440, 0xc04222b440)
        C:/Go/src/runtime/hashmap.go:340 +0x250 fp=0xc04222b3f8 sp=0xc04222b3b0
reflect.mapaccess(0x815560, 0xc0421ee510, 0xc042d9efc0, 0xc0421ee510)
        C:/Go/src/runtime/hashmap.go:1008 +0x46 fp=0xc04222b430 sp=0xc04222b3f8
reflect.Value.MapIndex(0x815560, 0xc0421e56b8, 0x195, 0x7e6820, 0xc042d9efc0, 0x98, 0x80a0c0, 0xc04207b9f0, 0x16)
        C:/Go/src/reflect/value.go:1040 +0x12f fp=0xc04222b4b8 sp=0xc04222b430
encoding/json.(*mapEncoder).encode(0xc04202e790, 0xc043e88dc0, 0x815560, 0xc0421e56b8, 0x195, 0x100)
        C:/Go/src/encoding/json/encode.go:646 +0x4f7 fp=0xc04222b610 sp=0xc04222b4b8
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc043e88dc0, 0x815560, 0xc0421e56b8, 0x195, 0x100)
        C:/Go/src/encoding/json/encode.go:662 +0x6b fp=0xc04222b650 sp=0xc04222b610
encoding/json.(*structEncoder).encode(0xc0422a6150, 0xc043e88dc0, 0x831220, 0xc0421e56a0, 0x199, 0x100)
        C:/Go/src/encoding/json/encode.go:601 +0x25a fp=0xc04222b7b0 sp=0xc04222b650
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc043e88dc0, 0x831220, 0xc0421e56a0, 0x199, 0xc0421e0100)
        C:/Go/src/encoding/json/encode.go:615 +0x6b fp=0xc04222b7f0 sp=0xc04222b7b0
encoding/json.(*ptrEncoder).encode(0xc04202e798, 0xc043e88dc0, 0x870320, 0xc0421e56a0, 0x16, 0x870100)
        C:/Go/src/encoding/json/encode.go:742 +0xea fp=0xc04222b830 sp=0xc04222b7f0
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc043e88dc0, 0x870320, 0xc0421e56a0, 0x16, 0xc0421e0100)
        C:/Go/src/encoding/json/encode.go:747 +0x6b fp=0xc04222b870 sp=0xc04222b830
encoding/json.(*encodeState).reflectValue(0xc043e88dc0, 0x870320, 0xc0421e56a0, 0x16, 0x100)
        C:/Go/src/encoding/json/encode.go:307 +0x89 fp=0xc04222b8a8 sp=0xc04222b870
encoding/json.(*encodeState).marshal(0xc043e88dc0, 0x870320, 0xc0421e56a0, 0x100, 0x0, 0x0)
        C:/Go/src/encoding/json/encode.go:280 +0xbf fp=0xc04222b8e0 sp=0xc04222b8a8
encoding/json.Marshal(0x870320, 0xc0421e56a0, 0x0, 0xc04207d338, 0xc0421ee450, 0xc04207d310, 0xb3e850)
        C:/Go/src/encoding/json/encode.go:145 +0x96 fp=0xc04222b928 sp=0xc04222b8e0
github.com/iopred/bruxism/playedplugin.(*playedPlugin).Save(0xc0421e56a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/github.com/iopred/bruxism/playedplugin/playedplugin.go:75 +0x3e fp=0xc04222b970 sp=0xc04222b928
github.com/iopred/bruxism.(*Bot).Save(0xc04200d480)
        C:/Go/src/github.com/iopred/bruxism/bot.go:112 +0x196 fp=0xc04222bba8 sp=0xc04222b970
main.main()
        C:/Go/src/github.com/iopred/bruxism/cmd/bruxism/main.go:190 +0x171b fp=0xc04222bf38 sp=0xc04222bba8
runtime.main()
        C:/Go/src/runtime/proc.go:183 +0x1f0 fp=0xc04222bf90 sp=0xc04222bf38
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc04222bf98 sp=0xc04222bf90

goroutine 5 [syscall, 47 minutes]:
os/signal.signal_recv(0x0)
        C:/Go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        C:/Go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        C:/Go/src/os/signal/signal_unix.go:28 +0x48

goroutine 34 [sleep, 1 minutes]:
time.Sleep(0xdf8475800)
        C:/Go/src/runtime/time.go:59 +0xef
github.com/iopred/bruxism.(*YouTube).pollMessages(0xc0420e54a0, 0xc04236e180)
        C:/Go/src/github.com/iopred/bruxism/youtube.go:182 +0x62f
created by github.com/iopred/bruxism.(*YouTube).pollBroadcasts
        C:/Go/src/github.com/iopred/bruxism/youtube.go:143 +0x9e

goroutine 35 [select, 47 minutes]:
github.com/iopred/bruxism.(*YouTube).handleRequests(0xc0420e54a0)
        C:/Go/src/github.com/iopred/bruxism/youtube.go:305 +0xd30
created by github.com/iopred/bruxism.(*YouTube).Open
        C:/Go/src/github.com/iopred/bruxism/youtube.go:378 +0x3a3

goroutine 49 [IO wait, 1 minutes]:
net.runtime_pollWait(0xf890f0, 0x72, 0xc043e91c88)
        C:/Go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0xc0421fe2f0, 0x72, 0xc043e91c88, 0xc0421f5660)
        C:/Go/src/net/fd_poll_runtime.go:73 +0x3f
net.(*ioSrv).ExecIO(0xc04202e208, 0xc0421fe1e0, 0x8a92bd, 0x7, 0x97d4f8, 0xc04203a368, 0xc000000000, 0x421f5770)
        C:/Go/src/net/fd_windows.go:171 +0x186
net.(*netFD).Read(0xc0421fe180, 0xc042324000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:426 +0x14a
net.(*conn).Read(0xc04202e220, 0xc042324000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        C:/Go/src/net/net.go:173 +0x77
crypto/tls.(*block).readFromUntil(0xc0421ef0b0, 0x2e20000, 0xc04202e220, 0x5, 0xc04202e220, 0xc0421fe298)
        C:/Go/src/crypto/tls/conn.go:472 +0x98
crypto/tls.(*Conn).readRecord(0xc0420ff880, 0x97dc17, 0xc0420ff980, 0xc04203a000)
        C:/Go/src/crypto/tls/conn.go:574 +0xcb
crypto/tls.(*Conn).Read(0xc0420ff880, 0xc042327000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        C:/Go/src/crypto/tls/conn.go:1109 +0x11d
bufio.(*Reader).fill(0xc0421f1620)
        C:/Go/src/bufio/bufio.go:97 +0x113
bufio.(*Reader).Read(0xc0421f1620, 0xc042012578, 0x9, 0x9, 0xfef, 0x11, 0x0)
        C:/Go/src/bufio/bufio.go:209 +0x1c3
io.ReadAtLeast(0xb1f8e0, 0xc0421f1620, 0xc042012578, 0x9, 0x9, 0x9, 0xc0421f5c70, 0x544595, 0xc0420ff880)
        C:/Go/src/io/io.go:307 +0xab
io.ReadFull(0xb1f8e0, 0xc0421f1620, 0xc042012578, 0x9, 0x9, 0x0, 0x0, 0xc0421f5cc8)
        C:/Go/src/io/io.go:325 +0x5f
net/http.http2readFrameHeader(0xc042012578, 0x9, 0x9, 0xb1f8e0, 0xc0421f1620, 0x0, 0xc000000000, 0x665a4c, 0xc0423464a0)
        C:/Go/src/net/http/h2_bundle.go:779 +0x82
net/http.(*http2Framer).ReadFrame(0xc042012540, 0xc042c2ce40, 0x0, 0x0, 0x0)
        C:/Go/src/net/http/h2_bundle.go:1001 +0xab
net/http.(*http2clientConnReadLoop).run(0xc0421f5f70, 0x97d690, 0xc0421f5f70)
        C:/Go/src/net/http/h2_bundle.go:6017 +0xc2
net/http.(*http2ClientConn).readLoop(0xc0421fcb60)
        C:/Go/src/net/http/h2_bundle.go:5950 +0xad
created by net/http.(*http2Transport).newClientConn
        C:/Go/src/net/http/h2_bundle.go:5314 +0x710

goroutine 36 [chan receive, 47 minutes]:
github.com/iopred/bruxism/liveplugin.(*livePlugin).Run(0xc0421e5660, 0xc04200d480, 0xb281a0, 0xc0420e54a0)
        C:/Go/src/github.com/iopred/bruxism/liveplugin/liveplugin.go:64 +0x77
created by github.com/iopred/bruxism/liveplugin.(*livePlugin).Load
        C:/Go/src/github.com/iopred/bruxism/liveplugin/liveplugin.go:41 +0x1e7

goroutine 37 [sleep, 1 minutes]:
time.Sleep(0x1dcd6500)
        C:/Go/src/runtime/time.go:59 +0xef
github.com/iopred/bruxism/reminderplugin.(*ReminderPlugin).Run(0xc0421daa10, 0xc04200d480, 0xb281a0, 0xc0420e54a0)
        C:/Go/src/github.com/iopred/bruxism/reminderplugin/reminderplugin.go:230 +0x60
created by github.com/iopred/bruxism/reminderplugin.(*ReminderPlugin).Load
        C:/Go/src/github.com/iopred/bruxism/reminderplugin/reminderplugin.go:241 +0x91

goroutine 38 [chan receive, 47 minutes]:
github.com/iopred/bruxism.(*Bot).listen(0xc04200d480, 0xb281a0, 0xc0420e54a0, 0xc04201a9c0)
        C:/Go/src/github.com/iopred/bruxism/bot.go:79 +0xc4
created by github.com/iopred/bruxism.(*Bot).Open
        C:/Go/src/github.com/iopred/bruxism/bot.go:95 +0x38e

goroutine 68 [IO wait]:
net.runtime_pollWait(0xf88f70, 0x72, 0xc043d900e8)
        C:/Go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0xc0421fe470, 0x72, 0xc043d900e8, 0xc04222f778)
        C:/Go/src/net/fd_poll_runtime.go:73 +0x3f
net.(*ioSrv).ExecIO(0xc04202e208, 0xc0421fe360, 0x8a92bd, 0x7, 0x97d4f8, 0x7ca520, 0xc043c74158, 0x196)
        C:/Go/src/net/fd_windows.go:171 +0x186
net.(*netFD).Read(0xc0421fe300, 0xc0425e2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:426 +0x14a
net.(*conn).Read(0xc04202e258, 0xc0425e2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        C:/Go/src/net/net.go:173 +0x77
crypto/tls.(*block).readFromUntil(0xc042340c60, 0x2e20000, 0xc04202e258, 0x5, 0xc04202e258, 0x0)
        C:/Go/src/crypto/tls/conn.go:472 +0x98
crypto/tls.(*Conn).readRecord(0xc042344700, 0x97dc17, 0xc042344800, 0x453f70)
        C:/Go/src/crypto/tls/conn.go:574 +0xcb
crypto/tls.(*Conn).Read(0xc042344700, 0xc042363000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        C:/Go/src/crypto/tls/conn.go:1109 +0x11d
bufio.(*Reader).fill(0xc04243c2a0)
        C:/Go/src/bufio/bufio.go:97 +0x113
bufio.(*Reader).Peek(0xc04243c2a0, 0x2, 0xc04222fc90, 0x5a63fd, 0xc04222feb8, 0x5a6403, 0xc000000018)
        C:/Go/src/bufio/bufio.go:129 +0x69
github.com/gorilla/websocket.(*Conn).read(0xc0423297c0, 0x2, 0xc043980000, 0x0, 0xb1f960, 0xc043afe000, 0x7cace0)
        C:/Go/src/github.com/gorilla/websocket/conn_read.go:12 +0x47
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0423297c0, 0x0, 0x7e61e0, 0xc043d90060)
        C:/Go/src/github.com/gorilla/websocket/conn.go:689 +0x63
github.com/gorilla/websocket.(*Conn).NextReader(0xc0423297c0, 0xc043d2dec8, 0x4081ab, 0x7e2fa0, 0xc0423f02a0, 0x0)
        C:/Go/src/github.com/gorilla/websocket/conn.go:844 +0x64
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0423297c0, 0x1, 0xc043980000, 0x108, 0x600, 0x0, 0x0)
        C:/Go/src/github.com/gorilla/websocket/conn.go:921 +0x36
github.com/iopred/discordgo.(*Session).listen(0xc0423785a0, 0xc0423297c0, 0xc0423f02a0)
        C:/Go/src/github.com/iopred/discordgo/wsapi.go:140 +0x99
created by github.com/iopred/discordgo.(*Session).Open
        C:/Go/src/github.com/iopred/discordgo/wsapi.go:120 +0x399

goroutine 70 [sleep, 1 minutes]:
time.Sleep(0x1dcd6500)
        C:/Go/src/runtime/time.go:59 +0xef
github.com/iopred/bruxism/reminderplugin.(*ReminderPlugin).Run(0xc0421daaf0, 0xc04200d480, 0xb27f00, 0xc0421daa80)
        C:/Go/src/github.com/iopred/bruxism/reminderplugin/reminderplugin.go:230 +0x60
created by github.com/iopred/bruxism/reminderplugin.(*ReminderPlugin).Load
        C:/Go/src/github.com/iopred/bruxism/reminderplugin/reminderplugin.go:241 +0x91

goroutine 71 [chan receive, 47 minutes]:
github.com/iopred/bruxism/liveplugin.(*livePlugin).Run(0xc0421e56c0, 0xc04200d480, 0xb27f00, 0xc0421daa80)
        C:/Go/src/github.com/iopred/bruxism/liveplugin/liveplugin.go:64 +0x77
created by github.com/iopred/bruxism/liveplugin.(*livePlugin).Load
        C:/Go/src/github.com/iopred/bruxism/liveplugin/liveplugin.go:41 +0x1e7

goroutine 64 [select, 1 minutes]:
github.com/iopred/discordgo.(*Session).heartbeat(0xc0423785a0, 0xc0423297c0, 0xc0423f02a0, 0xa122)
        C:/Go/src/github.com/iopred/discordgo/wsapi.go:216 +0x326
created by github.com/iopred/discordgo.(*Session).onReady
        C:/Go/src/github.com/iopred/discordgo/discord.go:251 +0x97

goroutine 59 [chan receive, 1 minutes]:
github.com/iopred/bruxism.(*Bot).listen(0xc04200d480, 0xb27f00, 0xc0421daa80, 0xc04201bec0)
        C:/Go/src/github.com/iopred/bruxism/bot.go:79 +0xc4
created by github.com/iopred/bruxism.(*Bot).Open
        C:/Go/src/github.com/iopred/bruxism/bot.go:95 +0x38e`

**Comment by iopred** [comment]
So your bot command should look like:

bruxism -discordtoken "Bot <token>" -discordapplicationclientid <clientid>

The important thing is your token is prefixed with "Bot ", this was changed
by the discord devs a couple of weeks ago and bots will not connect without
it.

There's verbose output for the discord part of the bot, enable it by adding:

`session.LogLevel = discordgo.LogDebug` to line 183 of discord.go

**Comment by UnforeseenOcean** [comment]
Thanks for the help.
I still don't understand how to invite bot account to a server.

**Comment by iopred** [comment]
Visit: https://discordapp.com/oauth2/authorize?client_id=<bot client
id>&scope=bot

There you can invite the bot to a server you control.

**Comment by UnforeseenOcean** [comment]
Okay, thank you!

**Comment by iopred** [comment]
Send me an invite to a server with your bot.

**Comment by UnforeseenOcean** [comment]
https://discord.gg/yJAuPXf
Bot's name is Thorbie.
