### ISSUE TITLE
Problems with Heroku

### ISSUE THREAD

**Issue by kinngh** [iopred/bruxism#17]
I have been trying to deploy the app on heroku and keep getting issues about Heroku not being able to detect language for installation. I added Go buildpack, still no luck

**Comment by iopred** [comment]
I don't know enough about Heroku to help, but looking at the docs it seems that Heroku depends on a godep vendor file.
Happy to approve a PR that makes bruxism work on Heroku, but I feel like it's not going to be easy. Bruxism writes all it's data to files and loads files for it's YouTube oauth info, all that would need to be refactored to use a DB and environment vars.
