### ISSUE TITLE
Not wanting to install

### ISSUE THREAD

**Issue by popcorn9499** [iopred/bruxism#18]
Everytime i try to run the command go get github.com/iopred/bruxism/cmd/bruxism i get this [error.](http://pastebin.com/JCq55Hvi) I dont know what im doing wrong.

Im running ubuntu 16.04

**Comment by iopred** [comment]
Oh, that's really weird, it looks like your version of Go isn't installed properly.

**Comment by popcorn9499** [comment]
How would I go about installing it correctly?

**Comment by iopred** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04

This doc looks right, of course you want to install go 1.7 (and 1.8 in February)

**Comment by popcorn9499** [comment]
k i got that working now i have a diffrerent problem that is probly another id10t eror on my part anyways its just simply that when i put the youtubeoauth2config.json i get a bunch of things that pop up like [this](https://i.imgur.com/kuQtaMK.png) Then the next command you ask me to run is bruxism -youtubeauth  but i dont know what auth code you want me to input. is it the client id in the same page?
