### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by annareinike** [iopred/bruxism#19]
Hey iopred,
unfortunately I am experiencing some issues with the installation of Go on Mac OS X.
I downloaded and installed the Go Package for Mac OS X [here](https://golang.org/dl/). 
Then I tried to follow your instructions.

- `go get github.com/iopred/bruxism/cmd/bruxism` 
If I hit enter the terminal jumps immediately to the next line with no response.
- `go install github.com/iopred/bruxism/cmd/bruxism`
The same result as mentioned above. It jumps immediately to the next line.
 
Is it right that the terminal window doesn't give me any feedback if the installation works or if it's done?

- `cd $GOPATH/bin`
The command works. It changes the directory to `/bin`

Apparently the next step `bruxism -youtubeurl` won't work because the terminal didn't seem to recognize the command _bruxism_. I guess the installation with your _cmd package_ haven't worked properly otherwise the command _bruxism_ should work right?

Do you have any idea? Thanks in advance.

**Comment by iopred** [comment]
You might need to do `./bruxism -youtubeurl ......`

If you're in $GOPATH/bin, do `ls` and see if the `bruxism` command exists.

**Comment by annareinike** [comment]
`bruxism` doesn't exist in the `$GOPATH/bin` folder.

**Comment by iopred** [comment]
hmm, that's weird, try:

`go run github.com/iopred/bruxism/cmd/bruxism -youtubeurl ....`

**Comment by annareinike** [comment]
`go run: no go files listed`

**Comment by iopred** [comment]
Hmm, you'll need to be in $GOPATH to do that.

Do files exist in:

$GOPATH/src/github.com/iopred/bruxism?

**Comment by annareinike** [comment]
If I'm trying to run your command `go run github.com/iopred/bruxism/cmd/bruxism -youtubeurl` in $GOPATH I get the same error as above.

Yes, files exist in `$GOPATH/src/github.com/iopred/bruxism`.

**Comment by iopred** [comment]
lol sorry!

`go run github.com/iopred/bruxism/cmd/bruxism/main.go -youtubeurl ....`

**Comment by annareinike** [comment]
Don't get me wrong but shouldn't I be in the `src` folder to run that command? Because my $GOPATH variable is set to `/Users/annareinike/go`. But in the folder `go` isn't a `github.com` folder?

**Comment by iopred** [comment]
yup, sorry just spitballing here, I rarely use go run, sorry! I assumed it
worked like install.

**Comment by annareinike** [comment]
No problem - I'm grateful you help me and finally I got a response that some files are missing.

**Comment by annareinike** [comment]
Even after some troubleshooting I wasn't able to get the bot working.

- Could not open avatars directory: open avatars: no such file or directory
- Could not open emoji directory: emoji/google open emoji/google: no such file or directory
- Could not open emoji directory: emoji/twitter open emoji/twitter: no such file or directory
- Could not open rooms directory: open rooms: no such file or directory
- Could not open characters directory: open characters: no such file or directory
- open youtubeoauth2config.json: no such file or directory

But why are those files are missing? Aren't these files part of the package I downloaded?
Additionally the `youtubeoauth2config.json` is already in the `users/annareinike/go/bin` but I get the error anyway.

**Comment by iopred** [comment]
I guess it needs to run from bin/

The install command should be tried again I guess. I haven't tried with go
run, sorry for the bad advice.

For the emoji read the readme in the emojiplugin dir.

The comic plugin needs a lot of data that I don't provide, that's why I
dont include it in the master branch.

**Comment by annareinike** [comment]
Okay the emoji stuff is in the `bin/emoji` dir.
Where do I download the comic plugin data?

So `go install github.com/iopred/bruxism/cmd/bruxism` again and then trying to run it out of the bin dir with `go run github.com/iopred/bruxism/cmd/bruxism/main.go -youtubeurl`?

**Comment by iopred** [comment]
The goal is to run the `bruxism` binary from $GOPATH/bin, where all the assets live.

**Comment by annareinike** [comment]
In the `$GOPATH/bin` is a `bruxism` Unix executable file. I guess you meant this.

**Comment by iopred** [comment]
Yeah, now you can do `./bruxism` from $GOPATH/bin

**Comment by annareinike** [comment]
That works with some errors:
Could not open avatars directory: open avatars: no such file or directory
Could not open rooms directory: open rooms: no such file or directory
Could not open characters directory: open characters: no such file or directory

But I got the auth link which I paste into my browser and confirm. Now I run `./bruxism -youtubeauth 123` `http://localhost:4242/youtube/callback?state=state&code=123` right?

**Comment by iopred** [comment]
Sorry, I have removed the comic plugin from master (I thought I had done it previously) doing: 
`go get -u github.com/iopred/bruxism/cmd/bruxism` will fix those last remaining warnings.

**Comment by annareinike** [comment]
Thank you so much. How does the bot work after I confirm the auth code with `bruxism -youtubeauth <AUTH CODE>`?
Is it listening the livestream chat and if one of those messages it retrieves is a trigger command then it fires a predefined message?

**Comment by iopred** [comment]
If you're using this for YT, you should run the bot:

Now you're authed you can just do:

`./bruxism -youtubechannelids <yourchannelid>`

The bot will then respond to:

`@<botname> <command>`

Because my bots name is Septapus I usually test with:

`@Septapus topstreamers`

**Comment by annareinike** [comment]
But the YouTube API only allows me to get data from my own livestream right? So I have to do a livestream and then test the bot?

**Comment by iopred** [comment]
bruxism works fine as a chat bot in other peoples chats, as it only needs to read public messages, however it's recommended to give the bot moderation privileges so that it isn't rate limited.

The YouTube API flow you did allows bruxism to post messages as your account.

**Comment by annareinike** [comment]
Got it. Should I do an extra account for the bot or is it possible if I allow bruxism to post on the behalf of the streamer's account?

**Comment by iopred** [comment]
It's usually good to make an extra account, then you get to name it :)

PS. if you really just want Septapus and don't want the hassle of hosting it yourself, you can visit: youtube.septapus.com and invite it to your streams.

**Comment by annareinike** [comment]
Yeah thanks but at the moment my ambition is to host and configure it on my own. 
One of reasons why I promise myself not to use Nightbot ;).
Seems that I have to stream to test the bot. What is the purpose of that livechat window in the [Livechat Dashboard](https://www.youtube.com/live_dashboard)?

**Comment by iopred** [comment]
It's there so you can have one window open on another monitor so you can view chat and stream health etc.

**Comment by annareinike** [comment]
That makes sense - mostly used the live chat popup. 
Shouldn't the bot respond to my command in that live chat dashboard if I write for instance `@annareinike topstreamers`?

**Comment by iopred** [comment]
The bot is made to monitor channels, so it polls the streaming state of all the channel id's you provide every 5 minutes, it won't be able to find streams to join if they are not live. (unlisted won't work either sadly).

If you wanted to make code modifications, in main.go, right after `bot.Open()` you could call `youtube.Join('videoid')` and use your current stream now video id.

You get that video id from your offline stream now page, so for example mine:
https://www.youtube.com/channel/UCGmC0A8mEAPdlELQdP9xJbw/live

Right click the player: copy video url: https://youtu.be/27jl9d1oc1g

You take the last bit, so the line of code would be:

`youtube.Join('27jl9d1oc1g')`

**Comment by annareinike** [comment]
Finally the bot works without any errors but the terminal window only outputs `<videoid> annareinike: @annareinike topstreamers`. But the chat didn't receive any answer from the bot?

**Comment by iopred** [comment]
annarenike is the account you oauthed?

You can also try `@<botname> help` or `@<botname> info` etc.

**Comment by annareinike** [comment]
Exactly. None of those commands worked for me. I only receive the messages. But doesn't that mean the oauth worked? Otherwise the bot coudn't listening right?

**Comment by iopred** [comment]
Yeah if the bot is seeing messages it should be able to respond to them.
The only thing I can think is that you're spelling the bots name wrong, or maybe the bot's name has a space in it? (I've never tested that)

Easiest thing to do is to change the command prefix to !, change the following function in youtube.go

```
func (yt *YouTube) CommandPrefix() string {
	return fmt.Sprintf("@%s ", yt.UserName())
}
```

to:

```
func (yt *YouTube) CommandPrefix() string {
	return "!"
}
```

Then you can do `!topstreamers` or `!help`

**Comment by annareinike** [comment]
But the bots name is the oauthed accounts name isn't it? So I oauthed with the account ’annareinike’ it should be working with ’@annareinike !topstreamers’?

**Comment by iopred** [comment]
if you don't make the code modification:
`@annareinike topstreamers`
if you make the modification:
`!topstreamers`

When you did the oauth flow, did you perhaps click on a different YT account?

The account could also be unable to comment I guess, if you sign in to that YT account, can you send messages?

**Comment by annareinike** [comment]
Alright. Hm do you know how those brand accounts behave in that case? Because I have a main account but without a YouTube channel and with that account I maintain the brand account which has a YouTube account.

**Comment by iopred** [comment]
Yeah, you need a YT account to send messages, my guess is you selected your
main account when you oauthed, instead of your brand. Redo the original
steps to generate a new auth key.

**Comment by annareinike** [comment]
Pretty sure I selected the right one but I'll give it a try.
What is with the oauth credentials which I got from the Google Console? Are these independent from the YouTube accounts?

**Comment by iopred** [comment]
That's linked to your Google account, basically your account has a certain amount of Quota, but it doesn't restrict the accounts you can use. With those credentials, you could post on behalf of any account (if you convinced them to do the oauth flow)

**Comment by annareinike** [comment]
Now I selected the right account and change the command prefix to "!" but the bot doesn't respond. Man it's frustrating - you helped me out so much and it will not work.

**Comment by iopred** [comment]
In main.go you could try sending a message not tied to a command:

youtube.SendMessage('<videoid>', 'message')

That should debug whether or not it's the command system.

You could also do:

fmt.Sprintf(youtube.UserName()) to make sure the bot is acting as the right
account.

But if you're seeing messages in the console, I think it's something with
your account.

**Comment by iopred** [comment]
(also try !help or !info)

**Comment by annareinike** [comment]
I pasted both code snippets after `bot.Open()` in main.go and nothing happened.
`fmt.Sprintf(youtube.UserName())` the bot should output its own username in the console right?
Do you have a suggestion whats wrong with my account so I can't send messages?

**Comment by iopred** [comment]
Did the bots username print?

All I can think is that the account is being rate limited, so I would suggest triggering the command with a different account.

Other than that, I can't really explain why it's not posting, I could try post on that video with my own bot? Likely not tonight though sorry :(

**Comment by iopred** [comment]
Also sorry: fmt.Println(youtube.UserName()) is the right code, sorry again, remote debugging is hard as heck.

**Comment by annareinike** [comment]
No the username didn't print :(
For explanation:
```
src/github.com/iopred/bruxism/cmd/bruxism/main.go

// Start all our services.
bot.Open()
youtube.SendMessage('<videoid>', 'test')
fmt.Println(youtube.UserName())
```
What do you mean with rate limited? I trigger the command with the streamers account so why am I limited? Yeah sure. Our time difference is about 10 hours so good night. Maybe I can contact you on Discord instead of spamming the comment section?

**Comment by bwmarrin** [comment]
@annareinike yeah, hop on Discord.  There's a Go server and iopred and many others are there that can help get you going if you want.  https://discord.gg/0f1SbxBZjYq9jLBk

**Comment by iopred** [comment]
Yeah join the discord would be right.

For the SendMessage thing, you need to actually send the message to the video:

youtube.SendMessage('oe34snthuoe', 'test')

As for rate limiting, if you're the owner of the video, then that is not the case.

**Comment by iopred** [comment]
Worked it out over Discord. Updated the README to reflect pain points we found setting up for YouTube.
