### ISSUE TITLE
Bot responds to edits for comicgen plugin

### ISSUE THREAD

**Issue by baughj** [iopred/bruxism#20]
This seems like an undesirable behavior for the comicgen plugin in particular, as it allows a user to quickly spam a channel:

`@septapus comic 3`
*displays comic*
edit original message, change to `@septapus comic 2`
*displays another comic*
(repeat ad nauseam)

This can be used to spam the crap out of a Discord server (which is why I'm reporting it). 

Is there a way this plugin in particular might be fixed to ignore edits? I would contribute a fix but I know absolutely nothing of go.

**Comment by iopred** [comment]
Spamming should be moderated by you.

Edits are extremely useful when someone types the incorrect command but
want to fix it.

The comic plugin could be made as an exception, but that in itself could be
confusing.

**Comment by baughj** [comment]
I believe that https://github.com/iopred/bruxism/commit/dbe7e05f358bc16180851a2b7b616e2dabdb45f2 is sufficient to close this issue.
