### ISSUE TITLE
bruxism bot not responding to youtube commands?

### ISSUE THREAD

**Issue by adamalf** [iopred/bruxism#7]
I'm probably doing it wrong. 

I have successfully set up bruxism with youtube and got it to where it is relaying the text from chat into the console of the server like this:

2016/07/29 17:12:45 <10923810239803981weoiruweoriuwroiu423098> Testingthebot: !Help remind
2016/07/29 17:12:45 <120984312309182ukirroui34yweyw5y23457575> Testingthebot: !help remind

But nothing happens in the actual youtube chat window. I would expect the "Testingthebot" account to reply with something? I am posting the !Help remind message as the bot.  

If you could help answer this, I would like to contribute to the wiki (maybe with some screenshots and simple example for oath) to make it easier for people get this set up.

Thanks!

**Comment by iopred** [comment]
The bot ignores messages from itself, you should post '!help remind' from
your own account. A nice way to do this is to log in as another account in
an incognito window.

**Comment by adamalf** [comment]
Thanks, I'll give that a try right now. Is there currently a way to restrict who the bot will accept commands from? We would like to try to use it for reminders, but probably need to restrict who can set them.

**Comment by adamalf** [comment]
P.S. I'd never heard of the "go" language before this project. When reading your instructions I thought maybe you were saying "go get" ... then thinking to myself that's not how you call "git" :)   Once I get it set up I'll try to post to the wiki here if it will let me.

**Comment by iopred** [comment]
It would be easy to modify the reminder plugin to only accept commands from
moderators.
service.IsModerator works on YT.

**Comment by adamalf** [comment]
Problems still....

if  `!help remind` should output something to the channel (written to channel by the user that granted offline access) still doesn't appear to be working.  Here's what I am doing:

1. log in to browser on PC1 and open the live streaming youtube channel (which is not owned by bot user)
2. run  ./bruxism -youtubeurl   from the server  (bruxism generates the URL)
3. copy/paste the bruxism url into window as the bot user 
4. I approve the access request from google/youtube (it asks for offline access)
5. [my redirect code for the oauth json file is in php and below]... it errors, but it does generate the auth code. I copy the code to clipboard
6. at server I run:   ./bruxism -youtubeauth [paste the code] -youtubelivevideoids [the id of the live video]
7. Bruxism now starts and seems to be listening since commands to the video chat room are relayed to console as explained in original post here.  The bot user is logged in to the channel as well.
8. Using PC2, I log in as a second user (with moderator access) and type !help remind or !Help remind, but nothing happens.

**Comment by adamalf** [comment]
service.IsModerator -- great! I saw that in the code. Once I get it working, I'll definitely do that.

**Comment by iopred** [comment]
Ah I'm sorry, I changed the command prefix for YouTube a while back, atm
it'll respond to:

@botname help remind

If you want to change it back to !, change this line:

https://github.com/iopred/bruxism/blob/master/youtube.go#L533

to:

return "!"

You can just edit that line locally, the file will be in:

$GOPATH/src/github.com/iopred/bruxism/youtube.go

**Comment by iopred** [comment]
Also, you don't need to do the -youtubeurl step after the first time you
auth just:

./bruxism -youtubelivevideoids <videoid>

**Comment by adamalf** [comment]
holy cow,  it works! Fantastic.

Do you have a pizza donation link?  :)

**Comment by adamalf** [comment]
It looks fairly easy to write these plugins too.  I'd like to write something for some commonly repeated notes as well...  like I can tell the bot   @botname message1  and it will dump message1 contents to channel, etc.

**Comment by iopred** [comment]
Oh that should be very easy indeed, you could even write a plugin that
allows you to set message commands like:
!addcommand donate To donate click the $ icon in chat!

Then regular folks could do:
!donate

Also, the power of bruxism is that any plugin you write also works on
Twitch, Discord, IRC and Slack! :)

**Comment by adamalf** [comment]
oh no, I meant to donate to YOU... (thanks for the help!)   Yes, it's a very cool project!

Problem I'm having now is my "bot" account is using  FirstName LastName, but as a bot of course I'd like a short name. Trying to get it to use displayname but no dice.

**Comment by adamalf** [comment]
but yes, we have a need for in channel donations too, so that'll be cool to write up latersoon as well :)

**Comment by adamalf** [comment]
oh hmm for my displayname issue maybe I'll just switch it back to !command as you suggested.

**Comment by adamalf** [comment]
!faq [faqname]     -- that's what I need to write. That's pretty much what I was thinking about with message1, etc. above.

**Comment by adamalf** [comment]
I'm using your two instructions for installation:
`go get github.com/iopred/bruxism/cmd/bruxism

go install github.com/iopred/bruxism/cmd/bruxism`

I deleted the previously compiled bruxism file then edited L533 in youtube.go file of the src directory and then re-ran 
`go install github.com/iopred/bruxism/cmd/bruxism`

It complained about fmt not being used (which I assumed was good) but the resulting bruxism file still wants to be addressed @botname and doesnt respond to "!"

I guess that's not how I should recompile the bruxism file when I make changes?

**Comment by iopred** [comment]
That's the correct thing to do, you may need to delete the pkg/
directory... don't ask why :|
