### ISSUE TITLE
septapus not doing anything

### ISSUE THREAD

**Issue by PaladinBrewer** [iopred/bruxism#9]
Hello,

So I installed septapus onto my discord server, I see it there (though offline if that matters). I've tried @septapus help, @septapus comic 5, @septapus stats etc etc and it isn't doing anything, is there something else I need to do to set it up?

**Comment by iopred** [comment]
You added Septapus, or you're running an instance of Bruxism?

**Comment by iopred** [comment]
Oh, he was down, should be fixed now.
